version: '3.9'

services:
  django:
    build: .
    command: sh -c "
      python manage.py makemigrations
      && python manage.py migrate  
      && gunicorn --bind 0.0.0.0:8000 alloutjob.wsgi"
    volumes:
      - .:/All-OutJob
    expose:
      - 8000
    env_file:
      - .env
  
  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose: 
      - 5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  nginx:
    image: nginx:1.19.8-alpine
    depends_on: 
      - django
    ports: 
      - "80:80"
    volumes:
      - ./static:/var/www/html/static
      - ./nginx-conf.d/:/etc/nginx/conf.d

  celery:
    build: .
    command: celery -A alloutjob worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
    # environment variables declared in the environment section override env_file
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/4
      - CELERY_BACKEND=redis://redis:6379/4
    depends_on:
      - django
      - redis

  redis:
    image: redis:5-alpine
  
volumes:
    pg_data:
    static: