# Generated by Django 4.0.5 on 2022-06-06 02:02

from django.db import migrations, models
import django.db.models.deletion
import scraper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='City name')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'City name',
                'verbose_name_plural': "City's names",
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Specialization')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Vacancy')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('description', models.TextField(verbose_name='Vacancy description')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.city', verbose_name='City')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.specialization', verbose_name='Specialization')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', models.JSONField(default=scraper.models.default_url)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.city', verbose_name='City')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.specialization', verbose_name='Specialization')),
            ],
            options={
                'unique_together': {('city', 'specialization')},
            },
        ),
    ]
